[libraries]
assertj-bom = { module = "org.assertj:assertj-bom", version = "3.27.6" }
assertj-core = { module = "org.assertj:assertj-core" }
archunit = { module = "com.tngtech.archunit:archunit", version = "1.4.1" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version = "2.46.0" }
nullaway = { module = "com.uber.nullaway:nullaway" }
nullaway-bom = { module = "com.uber.nullaway:nullaway-bom", version = "0.13.1" }
jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }
junit-bom = { module = "org.junit:junit-bom", version = "6.0.1" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
errorprone = { id = "net.ltgt.errorprone", version = "4.2.0" }
